### ISSUE TITLE
[ fatal] Unknown exception: /opt/fibaro/scenes/107.lua:354: attempt to index global 'decodedGlobalToken' (a number value)

### ISSUE THREAD

**Issue by jvd78** [gabordewit/SLIDE#2]
The dry run works well and I get a token from my slide. But when I push the button Initialize on the virtual device I get this error: [ fatal] Unknown exception: /opt/fibaro/scenes/107.lua:354: attempt to index global 'decodedGlobalToken' (a number value) I keep the Slidetoken variable empty as told in the readme and followed all the steps.

Has anyone an idea to solve this error?

Thanks in advance!

Best,

JvD

**Comment by gabordewit** [comment]
Hi JvD,

I was hoping you can help me with two question to get started:

- do you see this error in the virtual device debug or in the scene log output?

- When did you download the Lua code and tried to get it working?

I have been debugging this issue with another user and have hopefully corrected the mistake that was causing this. You can also already check some other things as well:

- Did you put the Dryrun and setindividualSlide in the scene back to false before initializing the virtual device?

- Can you validate slide_scene.lua rows 167 - 172 in your Fibaro skill to see if you have the following code there:   

`if dryrun then
    decodedGlobalToken = authData
    else 
    retrieveToken = fibaro:getGlobalValue("Slidetoken")
    decodedGlobalToken = json.decode(retrieveToken)
    end`

Based on the error I think the global value is still 0 (the value it gets while creating an empty variable in the fibaro pane) which means that there is no token stored yet. 

Thanks and regards,

Gabor

**Comment by jvd78** [comment]
Hi Gabor,

I got this error in the output window of the scene and the code you sent was in the lua code. 

I don't know what I changed or did wrong, but the code is working now, after adding a new virtual device. I have only must changed the SlideToCheck value in Single_slide.vfib on different places, because the default value is slide3.

Thank you for you quick answer and support!

**Comment by gabordewit** [comment]
Hi JvD,

good to hear that it's working now and thanks for your feedback.

With an increase in users it will be interesting to see where the scene can be made more robust, e.g. the slide3 value has been changed back again to slide1 so at least the first slide should always work.

Let me know if you run into more issues or have ideas where to improve so I can look into making everything more robust!

Enjoy the slides!

Gabor

**Comment by jvd78** [comment]
Hi Gabor, it was for a short term unfortunately.I have the same error now, but nothing changed! It works for one day and then it stopped working.

Any ideas how to fix this?

Best regards

JvD

**Comment by jvd78** [comment]
Hi Gabor,

Any ideas how to fix the attempt to index global error? It happens again!

Thanks!

Best regards

JVD

**Comment by gabordewit** [comment]
Hi JVD,

would it be possible to do the following:
- would it be possible to send the full fibaro log that is generated when this happens?
- would it be possible to make a screenshot of your variable pane in fibaro to see the current values that are currently in place for Slides / slidesceneID / Slidetoken?
- And finally would it be possible to paste the current LUA code you have in your scene(minus your credentials off course :))?

Thanks to another user (with working fibaro slides just like me) there is a new instruction set, hoping to paste that later today.

thanks an regards,

Gabor

**Comment by jvd78** [comment]
Hi Gabor,

Here is the information you requested:

[DEBUG] 21:32:05: Requesting global variable to run authentication
[DEBUG] 21:32:05: Request refreshHousehold
[DEBUG] 21:32:05: 2020-06-16 21:32:05.112505 [ fatal] Unknown exception: /opt/fibaro/scenes/107.lua:354: attempt to index global 'decodedGlobalToken' (a number value)


See attached file for the log of the dryrun, the LUA code and a screenshot of the variables.

Thanks

Regards


Jim

[cid:db55254f-7bbd-429f-87e9-e20971ec3434@EURP190.PROD.OUTLOOK.COM]

Op 14 jun. 2020, om 12:44 heeft gabordewit <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:



Hi JVD,

would it be possible to do the following:

  *   would it be possible to send the full fibaro log that is generated when this happens?
  *   would it be possible to make a screenshot of your variable pane in fibaro to see the current values that are currently in place for Slides / slidesceneID / Slidetoken?
  *   And finally would it be possible to paste the current LUA code you have in your scene(minus your credentials off course :))?

Thanks to another user (with working fibaro slides just like me) there is a new instruction set, hoping to paste that later today.

thanks an regards,

Gabor

**Comment by gabordewit** [comment]
Hi Jim,

for some reason the attachments are not coming through in the Github e-mail reply, can you send them to my e-mail address  instead?

Then i'll reach out to you directly to get the issue resolved.

Thanks and regards,

Gabor

**Comment by gabordewit** [comment]
Hi Jim,

In the feature branch there should now be an increased robustness setting that checks if the decoded information is actually  available. I also added a check for NaN values and a loop in the virtual devices to check for data corruption every 12 hours.

Hope this fixes the issues you are seeing, especially the Fibaro reboot data corruption is aparently a known issue that has not been resolved by Fibaro themselves, so hope this helps a bit!

Thanks and regards,

Gabor

**Comment by jvd78** [comment]
Perfect Gabor, thank you very much!! I’ll change and test it at my side ASAP.

Best regards

Jim
